version: '3'

services:
  app:
    build: .
    image: podcast-search-app:latest
    container_name: podcast-search-app
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://search.getcrazywisdom.com