version: '3.8'

services:
  app:
    container_name: podcast-search-app
    build:
      context: .
      dockerfile: Dockerfile
    image: podcast-search-app:latest
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://search.getcrazywisdom.com
    restart: unless-stopped
    # Memory limits using older syntax for compatibility
    mem_limit: 1G